## DataFrames Check!!!

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import json
import warnings
# Ignore all warnings
warnings.filterwarnings("ignore")

### CommonSense QA

In [2]:
# Path to your CSV file
csv_file_path = r'C:\Users\Bia\OneDrive\Ambiente de Trabalho\TESE_2024\DATASETS TESE\FINAL DATASETS\ComSens train\ComSenQA_train.csv'

# Read the CSV file into a DataFrame
ComSense = pd.read_csv(csv_file_path)

In [4]:
ComSense.head()

,Question,A,B,C,D,E,Correct Option
0,The sanctions against the school were a punish...,ignore,enforce,authoritarian,yell at,avoid,A
1,Sammy wanted to go to where the people were. ...,race track,populated areas,the desert,apartment,roadblock,B
2,To locate a choker not located in a jewelry bo...,jewelry store,neck,jewlery box,jewelry box,boutique,A
3,Google Maps and other highway and street GPS s...,united states,mexico,countryside,atlas,oceans,D
4,"The fox walked from the city into the forest, ...",pretty flowers.,hen house,natural habitat,storybook,dense forest,C

In [6]:
ComSense.isna().sum()

Question          0
A                 0
B                 0
C                 0
D                 0
E                 0
Correct Option    0
dtype: int64

In [7]:
# Path to your CSV file
csv_file_path = r'C:\Users\Bia\OneDrive\Ambiente de Trabalho\TESE_2024\DATASETS TESE\FINAL DATASETS\ComSens train\ComSenQA_questions_final.csv'

# Read the CSV file into a DataFrame
ComSens_final = pd.read_csv(csv_file_path)

In [8]:
ComSens_final.head()

,Question,A,B,C,D,E
0,The sanctions against the school were a punish...,ignore,enforce,authoritarian,yell at,avoid
1,Sammy wanted to go to where the people were. ...,race track,populated areas,the desert,apartment,roadblock
2,To locate a choker not located in a jewelry bo...,jewelry store,neck,jewlery box,jewelry box,boutique
3,Google Maps and other highway and street GPS s...,united states,mexico,countryside,atlas,oceans
4,"The fox walked from the city into the forest, ...",pretty flowers.,hen house,natural habitat,storybook,dense forest

In [9]:
ComSens_final.isna().sum()

Question    0
A           0
B           0
C           0
D           0
E           0
dtype: int64

### MathQA

In [34]:
# Path to your CSV file
csv_file_path = r'C:\Users\Bia\OneDrive\Ambiente de Trabalho\TESE_2024\DATASETS TESE\FINAL DATASETS\MathQ train\MathQA_train.csv'

# Read the CSV file into a DataFrame
MathQA = pd.read_csv(csv_file_path)

In [35]:
MathQA.isna().sum()

index             0
Question          0
A                 0
B                 0
C                 0
D                 0
E                 0
Correct Option    0
Sub-Branch        0
dtype: int64

In [38]:
MathQA.tail()

,index,Question,A,B,C,D,E,Correct Option,Sub-Branch
29832,29832,a man invests some money partly in 10 % stock ...,1 : 2,3 : 5,4 : 5,16 : 15,none,A,Other
29833,29833,"average of 10 matches is 32 , how many runs on...",a ) 70,b ) 76,c ) 78,d ) 98,e ) 88,D,General
29834,29834,solve below question 2 x + 1 = - 23,- 8,- 9,- 12,- 4,12,C,General
29835,29835,calculate 85184 ÷ ? = 352,241,242,244,247,240,B,General
29836,29836,7.51 8.22 7.86 8.36 8.09 7.83 8.30 8.01 7.73 8...,four,six,nine,ten,twelve,E,General

In [36]:
# Path to your CSV file
csv_file_path = r'C:\Users\Bia\OneDrive\Ambiente de Trabalho\TESE_2024\DATASETS TESE\FINAL DATASETS\MathQ train\MathQA_questions_final.csv'

# Read the CSV file into a DataFrame
MathQA_final = pd.read_csv(csv_file_path)

In [37]:
MathQA_final.tail()

,Question,A,B,C,D,E
29832,a man invests some money partly in 10 % stock ...,1 : 2,3 : 5,4 : 5,16 : 15,none
29833,"average of 10 matches is 32 , how many runs on...",a ) 70,b ) 76,c ) 78,d ) 98,e ) 88
29834,solve below question 2 x + 1 = - 23,- 8,- 9,- 12,- 4,12
29835,calculate 85184 ÷ ? = 352,241,242,244,247,240
29836,7.51 8.22 7.86 8.36 8.09 7.83 8.30 8.01 7.73 8...,four,six,nine,ten,twelve

### MedQA

In [41]:
# Path to your CSV file
csv_file_path = r'C:\Users\Bia\OneDrive\Ambiente de Trabalho\TESE_2024\DATASETS TESE\FINAL DATASETS\MedCQA train\MedQA_train.csv'

# Read the CSV file into a DataFrame
MedQA = pd.read_csv(csv_file_path)

In [42]:
MedQA.isna().sum()

Question          0
A                 0
B                 0
C                 0
D                 0
Correct Option    0
Subject           0
Topic             0
dtype: int64

In [43]:
MedQA.head()

,Question,A,B,C,D,Correct Option,Subject,Topic
0,Chronic urethral obstruction due to benign pri...,Hyperplasia,Hyperophy,Atrophy,Dyplasia,C,Anatomy,Urinary tract
1,Which vitamin is supplied from only animal sou...,Vitamin C,Vitamin B7,Vitamin B12,Vitamin D,C,Biochemistry,Vitamins and Minerals
2,Per rectum examination is not a useful test fo...,Anal fissure,Hemorrhoid,Pilonidal sinus,Rectal ulcer,C,Surgery,Urology
3,Naglers reaction is shown by,Clostridium tetani,Clostridium botulinum,Clostridium perfringens,Clostridium septicum,C,Microbiology,Bacteriology
4,The pharmakokinetic change occurring in geriat...,Gastric absorption,Liver metabolism,Renal clearance,Hypersensitivity,C,Anatomy,General anatomy

In [44]:
# Path to your CSV file
csv_file_path = r'C:\Users\Bia\OneDrive\Ambiente de Trabalho\TESE_2024\DATASETS TESE\FINAL DATASETS\MedCQA train\MedQA_questions_final.csv'

# Read the CSV file into a DataFrame
MedQA_final = pd.read_csv(csv_file_path)

In [45]:
MedQA_final.isna().sum()

Question    0
A           0
B           0
C           0
D           0
dtype: int64

In [46]:
MedQA_final.head()

,Question,A,B,C,D
0,Chronic urethral obstruction due to benign pri...,Hyperplasia,Hyperophy,Atrophy,Dyplasia
1,Which vitamin is supplied from only animal sou...,Vitamin C,Vitamin B7,Vitamin B12,Vitamin D
2,Per rectum examination is not a useful test fo...,Anal fissure,Hemorrhoid,Pilonidal sinus,Rectal ulcer
3,Naglers reaction is shown by,Clostridium tetani,Clostridium botulinum,Clostridium perfringens,Clostridium septicum
4,The pharmakokinetic change occurring in geriat...,Gastric absorption,Liver metabolism,Renal clearance,Hypersensitivity

### MMLU

In [47]:
# Path to your CSV file
csv_file_path = r'C:\Users\Bia\OneDrive\Ambiente de Trabalho\TESE_2024\DATASETS TESE\FINAL DATASETS\MMLU\MMLU_train.csv'
# Read the CSV file into a DataFrame
LLMU = pd.read_csv(csv_file_path)

In [48]:
LLMU.isna().sum()

Question          0
A                 0
B                 0
C                 0
D                 0
Correct Option    0
Subject           0
dtype: int64

In [49]:
LLMU.head()

,Question,A,B,C,D,Correct Option,Subject
0,Identify the conclusion of the following argum...,It is hard not to verify in our peers the same...,"The arrogance of our consciousness, which in g...","Because of this, it is difficult to convince p...",It is difficult to convince people of the unco...,D,Logic
1,Select the best translation into predicate log...,Tdc,Tcd,Tcc,dTc,A,Logic
2,Select the best English interpretation of the...,Some large houses are bigger than some apartme...,Some houses are bigger than all large apartments.,Some large apartments are bigger than some hou...,Some houses are bigger thatn some large apartm...,C,Logic
3,Construct a complete truth table for the follo...,Valid,Invalid. Counterexample when G and H are true,Invalid. Counterexample when G is true and H i...,Invalid. Counterexample when H is true and G i...,A,Logic
4,Use the following key to translate the given ...,If it's not the case that both Izzy plays Mine...,If it's both not the case that Izzy plays Mine...,Izzy playing Minecraft and Ashleigh stopping b...,Russell's making dinner is a sufficient condit...,B,Logic

In [50]:
# Path to your CSV file
csv_file_path = r'C:\Users\Bia\OneDrive\Ambiente de Trabalho\TESE_2024\DATASETS TESE\FINAL DATASETS\MMLU\MMLU_questions_final.csv'
# Read the CSV file into a DataFrame
LLMU_final = pd.read_csv(csv_file_path)

In [51]:
LLMU_final.isna().sum()

Question    0
A           0
B           0
C           0
D           0
dtype: int64

In [52]:
LLMU_final.head()

,Question,A,B,C,D
0,Identify the conclusion of the following argum...,It is hard not to verify in our peers the same...,"The arrogance of our consciousness, which in g...","Because of this, it is difficult to convince p...",It is difficult to convince people of the unco...
1,Select the best translation into predicate log...,Tdc,Tcd,Tcc,dTc
2,Select the best English interpretation of the...,Some large houses are bigger than some apartme...,Some houses are bigger than all large apartments.,Some large apartments are bigger than some hou...,Some houses are bigger thatn some large apartm...
3,Construct a complete truth table for the follo...,Valid,Invalid. Counterexample when G and H are true,Invalid. Counterexample when G is true and H i...,Invalid. Counterexample when H is true and G i...
4,Use the following key to translate the given ...,If it's not the case that both Izzy plays Mine...,If it's both not the case that Izzy plays Mine...,Izzy playing Minecraft and Ashleigh stopping b...,Russell's making dinner is a sufficient condit...

### Philosophy

In [53]:
# Path to your CSV file
csv_file_path = r'C:\Users\Bia\OneDrive\Ambiente de Trabalho\TESE_2024\DATASETS TESE\FINAL DATASETS\philosophy pt\Philosophy_train.csv'
# Read the CSV file into a DataFrame
Phil = pd.read_csv(csv_file_path)

In [54]:
Phil.isna().sum()

Question          0
A                 0
B                 0
C                 0
D                 0
Correct Option    0
Subject           0
dtype: int64

In [55]:
Phil.head()

,Question,A,B,C,D,Correct Option,Subject
0,"De acordo com a ética utilitarista de Mill, me...","é correto, porque nenhuma lei proíbe a mentira","é incorreto, porque nunca se deve mentir","pode ser correto, dependendo das consequências","pode ser correto, mas isso não depende das con...",C,Philosophy
1,Identifique o argumento de autoridade.,É hoje bastante claro para os investigadores q...,A pesar de a ciência e a religião serem muito ...,N,D o mesmo modo que não sabemos definir bem-est...,B,Philosophy
2,«Alguns cozinheiros premiados são portugueses....,apenas é preciso apurar se a conclusão e a pre...,"é preciso conhecer, pelo menos, um português q...",é preciso saber se há cozinheiros premiados qu...,apenas é preciso verificar se a conclusão pode...,D,Philosophy
3,"S uponha que alguém, com a intenção de defende...",do boneco de palha,do falso dilema,ad hominem,do apelo à ignorância,A,Philosophy
4,"Segundo o relativismo cultural,",há verdades morais aceites por todos os povos ...,os juízos morais dependem das convenções de ca...,os hábitos e as tradições culturais não devem ...,a moralidade não é uma questão de convenção so...,B,Philosophy

In [56]:
# Path to your CSV file
csv_file_path = r'C:\Users\Bia\OneDrive\Ambiente de Trabalho\TESE_2024\DATASETS TESE\FINAL DATASETS\philosophy pt\Philosophy_questions_final.csv'
# Read the CSV file into a DataFrame
Phil_final = pd.read_csv(csv_file_path)

In [57]:
Phil_final.isna().sum()

Question    0
A           0
B           0
C           0
D           0
dtype: int64

In [58]:
Phil_final.head()

,Question,A,B,C,D
0,"De acordo com a ética utilitarista de Mill, me...","é correto, porque nenhuma lei proíbe a mentira","é incorreto, porque nunca se deve mentir","pode ser correto, dependendo das consequências","pode ser correto, mas isso não depende das con..."
1,Identifique o argumento de autoridade.,É hoje bastante claro para os investigadores q...,A pesar de a ciência e a religião serem muito ...,N,D o mesmo modo que não sabemos definir bem-est...
2,«Alguns cozinheiros premiados são portugueses....,apenas é preciso apurar se a conclusão e a pre...,"é preciso conhecer, pelo menos, um português q...",é preciso saber se há cozinheiros premiados qu...,apenas é preciso verificar se a conclusão pode...
3,"S uponha que alguém, com a intenção de defende...",do boneco de palha,do falso dilema,ad hominem,do apelo à ignorância
4,"Segundo o relativismo cultural,",há verdades morais aceites por todos os povos ...,os juízos morais dependem das convenções de ca...,os hábitos e as tradições culturais não devem ...,a moralidade não é uma questão de convenção so...

### SciQA

In [60]:
# Path to your CSV file
csv_file_path = r'C:\Users\Bia\OneDrive\Ambiente de Trabalho\TESE_2024\DATASETS TESE\FINAL DATASETS\SciQ train\SciQ_train.csv'
# Read the CSV file into a DataFrame
SciQA = pd.read_csv(csv_file_path)

In [61]:
SciQA.isna().sum()

Question          0
A                 0
B                 0
C                 0
D                 0
Correct Option    0
Main Branch       0
Sub-Branch        0
dtype: int64

In [62]:
SciQA.head()

,Question,A,B,C,D,Correct Option,Main Branch,Sub-Branch
0,What type of organism is commonly used in prep...,gymnosperms,protozoa,mesophilic organisms,viruses,C,Biology,Microbiology
1,What phenomenon makes global winds blow northe...,centrifugal effect,coriolis effect,muon effect,tropical effect,B,Earth Sciences,Atmospheric Science
2,Changes from a less-ordered state to a more-or...,reactive,unbalanced,exothermic,endothermic,C,Physics,Thermodynamics
3,What is the least dangerous radioactive decay?,gamma decay,alpha decay,beta decay,zeta decay,B,Physics,Nuclear and Particle Physics
4,Kilauea in hawaii is the world’s most continuo...,carbon and smog,greenhouse gases,smoke and ash,magma,C,Earth Sciences,Geology

In [63]:
# Path to your CSV file
csv_file_path = r'C:\Users\Bia\OneDrive\Ambiente de Trabalho\TESE_2024\DATASETS TESE\FINAL DATASETS\SciQ train\SciQ_questions_final.csv'
# Read the CSV file into a DataFrame
SciQA_final = pd.read_csv(csv_file_path)

In [64]:
SciQA_final.isna().sum()

Question    0
A           0
B           0
C           0
D           0
dtype: int64

In [65]:
SciQA_final.head()

,Question,A,B,C,D
0,What type of organism is commonly used in prep...,gymnosperms,protozoa,mesophilic organisms,viruses
1,What phenomenon makes global winds blow northe...,centrifugal effect,coriolis effect,muon effect,tropical effect
2,Changes from a less-ordered state to a more-or...,reactive,unbalanced,exothermic,endothermic
3,What is the least dangerous radioactive decay?,gamma decay,alpha decay,beta decay,zeta decay
4,Kilauea in hawaii is the world’s most continuo...,carbon and smog,greenhouse gases,smoke and ash,magma